title: "Black Blog"
author: "Jan Černý"
description: "Made with <b style=\"color: #f45;\">&lt;3</b>"
permalink: /:title/
lang: "en"
date_format: "%B %d, %Y"

# Layout

sidebar: true                # show a sidebar instead of the usual header
show_excerpts: false         # show article excerpts on the home page
show_related: true           # show the previous and next links after every post
show_description: true       # show the site description in the sidebar
show_logo: true              # always keep the site title visible
show_title: false

# Styling

minimal: false               # use simpler style
sidebar_limit: "60em"       # css limit of showing side bar

# Menu

navigation:
  - {file: "index.html", icon: home}
  - {file: "README.md", icon: address-card}

external:    # see http://fontawesome.com/icons
  - {title: References, icon: envelope, url: "/ref"}
  - {title: Meziklasí, icon: seedling, url: "http://www.meziklasi.cz/"}
  - {title: Repository, icon: github, url: "https://github.com/yagarea/blackblog"}
  - {title: Subscribe, icon: rss, url: "/feed.xml"}

references:
  - {title: Github, icon: github, url: "https://github.com/yagarea/"}
  - {title: StackOverflow, icon: stack-overflow, url: "https://stackoverflow.com/users/7274239/"}
  - {title: Reddit, icon: reddit, url: "https://www.reddit.com/user/yagarea"}
  - {title: Steam, icon: steam, url: "/ref"}

comments:
#  disqus: ""                # see https://disqus.com/
#  isso: ""                  # see https://posativ.org/isso/

plugins:
 - jekyll-feed
